### ISSUE TITLE
Manifest for the image?

### ISSUE THREAD

**Issue by kenpower** [pslade2/AugmentedCane#2]
Where can I get a more details about the image (O/S dependencies etc). 

The zendo link (https://zenodo.org/record/5508347) just has an img file.

Thanks

**Comment by pslade2** [comment]
Hi Ken,

I would suggest building from the latest Raspbian Image (I used a 2019 raspbian image) and installing the python dependencies for whichever script you are trying to run. Let me know if you have more questions!
